### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by pvinis** [zxbodya/rx-react-container#5]
Hello. Started using this after comparing it with rx-recompose. I have looked for ways to do rxjs with react native.

I just wanted to say thank you for making this library. Its great, and if you need help with something, Id be happy to help.

**Comment by zxbodya** [comment]
Happy to hear you like it ;)

would be curious hearing feedback about using it(like what is nice for you, what might be improve, maybe some related things)

**Comment by pvinis** [comment]
would here be the place to write?

**Comment by zxbodya** [comment]
Maybe email. But github issues also should be ok, if  you want to use it.

**Comment by pvinis** [comment]
@zxbodya do you have like discord or slack or something to write more directly?
i have some stuff like the way props are handled that i want to ask you, to see if you had this problem or something.

**Comment by zxbodya** [comment]
@pvinis replied in email
